UI Updated
priyajoshipj/LinkedInCloneFrontend pull request #2
Opened 2023-03-28 09:39 UTC by pushpendrakukreti

### Features

- Added homepage link to navbar logo 
- Removed search icon from search bar
- Only firstname to show in session dropown

2023-03-28 10:02 UTC, priyajoshipj requested changes
Please find below issue's
1) User won't able to clear search box and there should be a cancel button in search text box
so that user will on search box and clear search result.
2) User can search by friend by first and last name.
3) Friend list UI should be in horizontal order.

2023-03-28 12:29 UTC, pushpendrakukreti commented
> Updated following points

> 1. User won't able to clear search box and there should be a cancel button in search text box
>    so that user will on search box and clear search result.
> 2. User can search by friend by first and last name.
> 3. Friend list UI should be in horizontal order.  (will update this point in next PR)
> 4.  Fix backspacing issue in search box, it should be cleared properly.

2023-03-28 15:09 UTC, priyajoshipj requested changes

2023-03-28 15:09 UTC, priyajoshipj commented on src/scenes/navbar/index.jsx
> +    navigate(0);
why navigate(0) ?

2023-03-28 15:09 UTC, priyajoshipj commented on src/scenes/navbar/index.jsx
> +      <FlexBetween gap="1.75rem" height={"7vh"}>
try to avoid inline styles use classes instead

2023-03-28 15:09 UTC, priyajoshipj commented on src/scenes/navbar/index.jsx
>            <List class={searchUserList.length > 0 ? "search-box-container" : ""}>
you can optimized your code like this class={ `${searchUserList.length.length > 0  && "search-box-container" ` }

2023-03-28 15:16 UTC, priyajoshipj requested changes

2023-03-28 15:16 UTC, priyajoshipj commented on src/scenes/navbar/index.jsx
>      const savedUserResponse = await fetch(
please add try and catch to catch api error

2023-03-28 16:09 UTC, pushpendrakukreti commented on src/scenes/navbar/index.jsx
> +    navigate(0);
When we redirect to any profile, and search for another profile on same page it just updates the id in url not the page.
navigate(0) refreshes the page by taking current url.

2023-03-31 18:38 UTC, priyajoshipj approved these changes

2023-03-31 18:49 UTC, merged